### PR TITLE
Feat/colored

### PR DESCRIPTION
**Pull request by uggla**
Hello @bpetit ,

This is small PR to add some colors.
It was a test and an excuse to use the colored crate.
If you dislike it feel free to cancel this PR.

### CODE REVIEW

**Comment by bpetit** [comment]
Thanks ! I'll try that. I like the idea !

**Comment by uggla** [comment]
Yes a couple of emojis and colors make the shell a bit more funny. :)

**Comment by bpetit** [comment]
I'm wondering if it would be better to turn it on or off at will. I mean the verbosity of scaphandre can be controlled with -[v[v[v]]] and the logger. Here we are using println so it will be there by default, which may not suit all tastes and wishes.

What do you think ?

**Comment by uggla** [comment]
> I'm wondering if it would be better to turn it on or off at will. I mean the verbosity of scaphandre can be controlled with -[v[v[v]]] and the logger. Here we are using println so it will be there by default, which may not suit all tastes and wishes.
> 
I  would like a bit more verbosity. But this is a personal opinion. So I can understand if it is not shared.
The only argument I have to go in this way is the following one.
If you collect stdout and send that into a centralized log manager. I think it is good to send at least a line saying the process has started.

**Comment by bpetit** [comment]
As an alternative I've moved the fn scaphandre_header in lib.rs and made it optional with an option: --no-color

https://github.com/hubblo-org/scaphandre/blob/uggla-feat/colored/src/lib.rs#L66

WDYT ?

**Pull request merged**
