### PR TITLE
feat: Factorization exporter

### PR DESCRIPTION
**Pull request by uggla**
Factorization code is complete for prometheus and riemann exporters.
Documentation and naming efforts completed.

Please have a look, feedback welcomed.

### CODE REVIEW

**Comment by uggla** [comment]
@bpetit, I think I'm done with this MR.
Please have a look.

**Comment by bpetit** [comment]
I've tested and looked at your PR. This is great work, thanks a lot !

I only have a little concern that is pure semantics, first part of gen_host_metrics:

- scaph_self_socket_stats_nb
- scaph_self_socket_records_nb
- scaph_self_domain_records_nb
 
 in my opinion should be part of the gen_self_metrics one, as it only generates `scaph_self` metrics.
 
 What do you think ?

**Comment by uggla** [comment]
> I've tested and looked at your PR. This is great work, thanks a lot !
> 
> I only have a little concern that is pure semantics, first part of gen_host_metrics:
> 
>     * scaph_self_socket_stats_nb
> 
>     * scaph_self_socket_records_nb
> 
>     * scaph_self_domain_records_nb
> 
> 
> in my opinion should be part of the gen_self_metrics one, as it only generates `scaph_self` metrics.
> 
> What do you think ?

Hello, I agree it makes more sens.
We did a roughly split of methods, so yes it may need to be refined.

**Comment by bpetit** [comment]
I think we have a mismatch between prometheus and riemann expect to find as metric names.
[In the new metric generator interface](https://github.com/uggla/scaphandre/blob/feat/factorize_exporter/src/exporters/mod.rs#L466) we are defining the metric name as a concatenation between the name scaph_process_power_consumption_microwatts, the pid and the exe string.

I think this is how you defined it in the previous implementation of the riemann exporter: [l497](https://github.com/hubblo-org/scaphandre/blob/main/src/exporters/riemann.rs#L497)

In the prometheus exporter however we only used `scaph_process_power_consumption_microwatts` as a name and added pid and exe as labels. You know riemann better than me, maybe it is better that way for riemann metrics ?

For prometheus I think it's really better to have the current generic name with additional labels. If it is not goot for riemann, we have a topic to think about here. How to provide a generic interface that fits such different needs ? 

Even if we say riemann metrics can have a generic name for example, what guideline should we try to follow to avoid similar differences in the future ? Should we split the get_*_metric in different versions ? Or add options to choose how to compose the name of the metric ? Open debate here.

**Comment by uggla** [comment]
> I think we have a mismatch between prometheus and riemann expect to find as metric names.
> [In the new metric generator interface](https://github.com/uggla/scaphandre/blob/feat/factorize_exporter/src/exporters/mod.rs#L466) we are defining the metric name as a concatenation between the name scaph_process_power_consumption_microwatts, the pid and the exe string.
> 
> I think this is how you defined it in the previous implementation of the riemann exporter: [l497](https://github.com/hubblo-org/scaphandre/blob/main/src/exporters/riemann.rs#L497)

> 
> In the prometheus exporter however we only used `scaph_process_power_consumption_microwatts` as a name and added pid and exe as labels. You know riemann better than me, maybe it is better that way for riemann metrics ?

Yes you are right. Riemann needs to have different names otherwise it is the same metric updated again and again, despite the addition of different tags.

> 
> For prometheus I think it's really better to have the current generic name with additional labels. If it is not goot for riemann, we have a topic to think about here. How to provide a generic interface that fits such different needs ?

Sure, I did a mistake here. I think it is only on the process part which is affected.


> 
> Even if we say riemann metrics can have a generic name for example, what guideline should we try to follow to avoid similar differences in the future ? Should we split the get_*_metric in different versions ? Or add options to choose how to compose the name of the metric ? Open debate here.
> 

The name should be the one expected by prometheus. Then processing (concatenation) can be done in the Riemann part as it is specific for it.

It is more or less moving this part:
```rust
            let metric_name = format!(
                "{}_{}_{}",
                "scaph_process_power_consumption_microwatts",
                pid.to_string(),
                exe
```
From "generic" one to Riemann. So no big deal I think.

> In the current implementation prometheus is failing to collect metrics:
> 
> "invalid metric type "0:0H-events_highpri gauge"
> 
> as it tries to read lines like: "# TYPE scaph_process_power_consumption_microwatts_43070_kworker/0:3-events gauge"

Sorry not to have seen it on my side. Hopefully you get it. 🙀

**Comment by bpetit** [comment]
I'll fix it, no worries. I wanted to have your thoughts on this. Providing the generic name and asking exporters developers to add the suffix they need seems a good idea. I'll try something in that direction.

> Sorry not to have seen it on my side. Hopefully you get it. scream_cat

No worries, that's why I ask you to review my PRs too 😋 , we all miss stuff when we are the only one to look at it.
The PR is great anyway, this is going the right direction ! 🥳 

Thanks !

**Pull request merged**
