### PR TITLE
feat: Add service monitor on helm chart

### PR DESCRIPTION
**Pull request by mmadoo**
Allow configuration of service monitor in order to have metrics collected by an external prometheus

Signed-off-by: Nicolas Trangosi <nicolas.trangosi@dcbrain.com>

### CODE REVIEW

**Comment by mmadoo** [comment]
Is it possible to have a feedback on this PR ? 
If it is accepted, I could create new pull requests on the helm part of this project.

**Comment by bpetit** [comment]
Thanks a lot ! merging !

**Comment by damienvergnaud** [comment]
Oops, i missed this, 1 hour too late, 

Having the ability to add labels on this service-monitor object from the values of the chart would help configuration with already existing prometheus stack.

For example the kubernetes-prometheus stack (install Prom + Prom-operator + Grafana headless)
Will automatically grab  service-monitor objects with this label : 

```
labels:
  release: prometheus-stack
```

I'll love to engage with you on further PR @mmadoo you may ping me :+1:

**Comment by mmadoo** [comment]
> I'll love to engage with you on further PR @mmadoo you may ping me 👍
@damienvergnaud  I will try to work on this next week. I have other modifcations I would like to add on helm chart, but I was waiting for this PR to be merged.

**Pull request merged**
