### PR TITLE
Fix/domain order

### LINKED ISSUE #108: Consistently reports 0 W for DRAM consumption
## Bug description

Scaphandre reports 0 W as the DRAM consumption.

## Expected behavior

I hoped scaphandre would include DRAM measurements.

## Screenshots

Screenshot-2021-05-07T09:09:55

Screenshot-2021-05-07T09:27:00

## Environment

- **Linux distribution version**: Ubuntu 20.04.2
- **Kernel version**: 5.4.0-67-generic
- **CPU:** Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
- **Scaphandre version:** `a7b0159ce5135e2b25fe4c97a86434d30f6e0982` (self-built). Also tried pre-built docker image.

## Additional context

I realize that this may very well be the intended behavior, and not a bug (e.g. because the Intel RAPL sensor or powercap doesn't output RAM for this CPU make). I was mainly hoping to get clarifications into this - if it's something I will be able to fix (maybe I'm just operating scaphandre wrong or am missing something silly?), or if it's just the way it is. Thank you for having written this really useful tool!

Also, could it simply be because the memory usage is low, i.e. around 1GB used with 11GB buff/cached?

```bash
root@Ubuntu-2004-focal-64-minimal ~ # free -m
              total        used        free      shared  buff/cache   available
Mem:          31900        1381       19428         140       11090       29945
Swap:         16366           0       16366
```

### PR DESCRIPTION
**Pull request by PierreRust**
This should fix #108 and ensure that all detected domains are displayed. Let me know what you think.

Before merging, I'm wondering why the 'package' domain is not handled as the other domains ?  Is there any reason I'm missing ? I could try to change that but it would probably have an impact on all other exporters.

Besides, I have yet to check the Json exporter to check if the same fix is needed.

### CODE REVIEW

**Comment by PierreRust** [comment]
I've just added a fix for the json exporter, it was actually much simpler, we just needed to use the name field from the domain.

**Comment by wanecek** [comment]
I can confirm that this works on my computer, both for stdout and json exporters :+1:

**Comment by PierreRust** [comment]
Great news, thanks for the feedback @wanecek  !

**Review by bpetit — APPROVED** [review]
Seems good to me. Thanks a lot for that PR !

> Before merging, I'm wondering why the 'package' domain is not handled as the other domains ? Is there any reason I'm missing ? I could try to change that but it would probably have an impact on all other exporters.

Do you mean why it was not contained in the static list you got rid of ?

For bad reasons I think, pkg is a domain that is seen on pretty new hardware afaik. I didn't get an occasion to get it in my tests yet.

I also think PR #97 is not needed anymore thanks to this one. Am I right or did I forget something ?

**Pull request merged**
