### PR TITLE
:memo: Fix doc broken links

### PR DESCRIPTION
**Pull request by homersimpsons**
I used https://crates.io/crates/mdbook-linkcheck to find which links were broken.

I cannot seem to find the CI publishing the book to GitHub pages to include the check in the CI too.

### CODE REVIEW

**Comment by homersimpsons** [comment]
@bpetit Just a quick bump, do I have anything to change ?

**Comment by bpetit** [comment]
Should be good, thanks a lot. Merge is on the way !

**Review by bpetit — APPROVED** [review]

**Comment by bpetit** [comment]
Thanks for the reminder and the PR. On its way !

**Comment by bpetit** [comment]
Seems way better online ! Thanks !

**Pull request merged**
