### PR TITLE
Add Python binding for Scaphandre.

### PR DESCRIPTION
**Pull request by fvaleye**
# Description
- Add Python binding (>3.7) using `pyo3` to call Scaphandre Rust code from Python.
- Add the first version with the sensor `PowercapRAPL` as default.
- Expose 3 methods: `init`, `is_compatible` and `get_energy_consumption_measures`.
- Add Python documentation.
- Expose Rust version Scaphandre crate

# Documentation
- https://github.com/PyO3/pyo3
- https://github.com/PyO3/maturin

### CODE REVIEW

**Comment by fvaleye** [comment]
Hello @mrchrisadams 👋,

Not yet but that's the goal, call Scaphandre Rust codebase from Python 👍 

As a follow-up after this PR, we could publish the `scaphandre` Python package in [pypi](https://pypi.org/) and you could install it using `pip` as you described with `pip install scaphandre`. 

The documentation is already implemented in this PR so we could include documentation using [Sphinx](https://www.sphinx-doc.org/en/master/), any contributions on this would be welcomed!

**Comment by demeringo** [comment]
Hello, @fvaleye, do you plan to use Scaphandre in tracarbon ?

**Comment by fvaleye** [comment]
Hello @demeringo 👋,

If this PR is accepted and merged, yes 👍 

Using Scaphandre to get electrical power consumption metrics for [Tracarbon](https://github.com/fvaleye/tracarbon), the focus will be more on calculating the associated carbon emissions instead of redeveloping or integrating energy consumption sensors in it. This Python binding could be extended by exposing other Rust functions of Scaphandre and several use cases could be activated by having only Python as a requirement.

**Comment by mrchrisadams** [comment]
ok, thanks @fvaleye.

Oh neat - I had no idea Tracarbon existed!

We've been doing something similar - we've been building a library for getting carbon intensity from various providers of this data, to use with tooling like Scaphandre, and integrate into anything written in Go (i.e. schedulers like Nomad and K8s, and so on).

https://github.com/thegreenwebfoundation/grid-intensity-go

I'll look over Tracarbon, as previously I had been looking at tools like [codecarbon](https://codecarbon.io/) as a way for python apps to self describe their own resource footprint, but it ends up duplicating some of what Scaphandre already does, and if it's consuming output from Scaphandre, that feels like it reduces duplication of work 👍

**Comment by bpetit** [comment]
Hi @fvaleye !

Review is ok ! Sorry to ask about that so late, but could you reopen the exact same PR on dev please ? (I should have thought about it before)

**Pull request merged**
