### PR TITLE
fix: escape backslashes in metric labels

### PR DESCRIPTION
**Pull request by demeringo**
See #204

### CODE REVIEW

**Comment by demeringo** [comment]
Not directly linked to this PR, but some clippy check do not pass with Rust 1.66 toolchain.

I was testing with a local 1.65 which was more permissive.

Maybe the best way forward is to have a dedicated PR on `dev` to fix the warnings, then update _this_ PR with the changes.

**Comment by demeringo** [comment]
To be rebuild after PR #254 (that fixes the warnings) is merged to dev.

**Comment by demeringo** [comment]
Putting this PR on hold for a small rewrite:

@bpetit following the PR https://github.com/hubblo-org/scaphandre/pull/195 from @uggla (fixing #175) that was merged to release 0.5, we should 
- check if _yhis_ PR is still needed.
- If yes, update _this_ PR to make sure it does not conflict with what was merged.

**Comment by bpetit** [comment]
Sorry for the delay, then decrepancy on this one.

I think this is done through the other PRs.

Thanks !

**Pull request closed without merging**
